apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: haseena
  name: my-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: haseena
    spec:
      containers:
      - image: sedhu/project1:apache
        name: haseena
        ports:
        - name: haseena
          containerPort: 80      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: haseena
  name: haseena
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: haseena
